//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donate
    {
        public int IDdonate { get; set; }
        public Nullable<int> DonateMoney { get; set; }
        public string PersonDonateName { get; set; }
        public string Infor { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public string meta { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<bool> hide { get; set; }
    }
}
