//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CharityWebsiteEntities : DbContext
    {
        public CharityWebsiteEntities()
            : base("name=CharityWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<ContactInfor> ContactInfors { get; set; }
        public virtual DbSet<Donate> Donates { get; set; }
        public virtual DbSet<DuAn> DuAns { get; set; }
        public virtual DbSet<InforDonate> InforDonates { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<submenu> submenus { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
